---
spring:
  profiles:
    active: ${APP_PROFILE:default}
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization.WRITE_DATES_AS_TIMESTAMPS: true
    deserialization.ADJUST_DATES_TO_CONTEXT_TIME_ZONE: true
  data:
    mongodb:
      host: localhost
      port: 27017
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  security:
    basic:
      enabled: false



